ent-web/src/main/java/pl/sda/standalone/Controllers/BookAddController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.sda.standalone.Controllers;

import java.util.ArrayList;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import pl.sda.standalone.model.Book;
import pl.sda.standalone.BookBeanInterface;
import pl.sda.standalone.model.Author;

/**
 *
 * @author marecki
 */
@ManagedBean(name = "bookAddController")
@RequestScoped
public class BookAddController {

    private String name;
    private String authors;
    private int isbn;
    private int year;
    
    @EJB
    private BookBeanInterface bookBean;
    
    public BookAddController() {
    }
    
    public void addBook() {
        Book book = new Book();
        book.setName(name);
        book.setIsbn(isbn);
        book.setYear(year);
        
        String [] authorNames = authors.split(",");
        ArrayList<Author> booksAuthors = new ArrayList<>();
        
        for (String name : authorNames) {
            Author author = new Author();
            author.setName(name);
            ArrayList<Book> booksList = new ArrayList<Book>();
            booksList.add(book);
            author.setBooks(booksList);
            booksAuthors.add(author);
        }
        
        book.setAuthors(booksAuthors);
        bookBean.addBook(book);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public int getIsbn() {
        return isbn;
    }

    public void setIsbn(int isbn) {
        this.isbn = isbn;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public String getAuthors() {
        return authors;
    }

    public void setAuthors(String authors) {
        this.authors = authors;
    }
}

ent-web/src/main/java/pl/sda/standalone/Controllers/BookTableController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.sda.standalone.Controllers;

import java.util.List;
import java.util.stream.Collectors;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import org.modelmapper.ModelMapper;
import pl.sda.standalone.model.Book;
import pl.sda.standalone.BookBeanInterface;
import pl.sda.standalone.DTOs.AuthorDTO;
import pl.sda.standalone.DTOs.BookDTO;

/**
 *
 * @author RENT
 */
@ManagedBean(name = "bookTableController")
@RequestScoped
public class BookTableController {

    @EJB
    private BookBeanInterface bookBean;

    public BookTableController() {
    }

    public List<Book> getBooks() {
        return bookBean.getListOfBooks();
    }
    
    public String getAuthors(BookDTO b) {
        
        String authors = "";
        for (AuthorDTO a : b.getAuthors()) {
            authors += a.getName() + ", ";
        } 
        return authors.substring(0, authors.length() - 2);
    }
    
    public List<BookDTO> getBooksDTO() {
        
        List<Book> books = bookBean.getListOfBooks();
        List<BookDTO> collection;
        collection = books.stream().map(this::mapBook).collect(Collectors.toList());
        
        return collection;
    }
    
    public BookDTO mapBook(Book b) {
        
        ModelMapper mapper = new ModelMapper();
        BookDTO mappedBook = mapper.map(b, BookDTO.class);
        
        return mappedBook;
    }
}

ent-web/src/main/java/pl/sda/standalone/Controllers/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.sda.standalone.Controllers;

import java.io.Serializable;
import javax.ejb.EJB;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import pl.sda.standalone.UserBeanInterface;
import pl.sda.standalone.model.User;

/**
 *
 * @author RENT
 */
@ManagedBean(name = "loginController")
@SessionScoped
public class LoginController implements Serializable {

    private String userLogin;
    private String password;
    private boolean userLogged;
    private User user;

    @EJB
    private UserBeanInterface userBean;

    public LoginController() {
        userLogged = false;
    }

    public void login() {

        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);

        if (session.isNew()) {
            session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(true);
        }

        user = userBean.logIn(this.getUserLogin(), this.getPassword());

        if (user != null) {
            this.setUserLogged(true);
            if (user.getUser_role() == 1) {
                session.setAttribute("userRole", "admin");
            } else {
                session.setAttribute("userRole", "user");
            }
        }
    }

    public void logout() {
        this.setUserLogged(false);
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
//        session.setAttribute("isLogged", "false");
        session.invalidate();
    }

    public String getUserLogin() {
        return userLogin;
    }

    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isUserLogged() {
        return userLogged;
    }

    public void setUserLogged(boolean userLogged) {
        this.userLogged = userLogged;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public UserBeanInterface getUserBean() {
        return userBean;
    }

    public void setUserBean(UserBeanInterface userBean) {
        this.userBean = userBean;
    }
}

ent-web/src/main/webapp/account.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:body>
        <ui:composition template="templates/commonlayout.xhtml">
            <ui:define name="content">
                <h2>Moje konto</h2>
                <h4>Login: #{loginController.user.userLogin}</h4>
                <h4>Imię: #{loginController.user.firstName}</h4>
                <h4>Nazwisko: #{loginController.user.lastName}</h4>
                <h4>Adres: #{loginController.user.street}</h4>
                <h4>Miasto: #{loginController.user.city}</h4>
                <h4>Hasło: #{loginController.user.userPassword}</h4>
                <h4>Rola: #{loginController.user.user_role}</h4>
                <h:form><h:commandButton value="Wyloguj" action="#{loginController.logout()}"/></h:form>
                
                <h:dataTable value="#{rentControler.getPreviouslyRentedBooks(loginController.user)}" var="book">
                    <h:column>
                        <f:facet name="header">Nazwa</f:facet>
                        #{book.id}
                    </h:column>
                </h:dataTable>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

ent-web/src/main/webapp/addbook.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="templates/commonlayout.xhtml">
            <ui:define name="content">
                <h2>Dodaj książkę</h2>
                <h:form>
                    <div class="row">
                        <div class="col-md-3">Nazwa książki</div>
                        <div class="col-md-3"><h:inputText value="#{bookAddController.name}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Autorzy</div>
                        <div class="col-md-3"><h:inputText value="#{bookAddController.authors}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">ISBN</div>
                        <div class="col-md-3"><h:inputText value="#{bookAddController.isbn}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Data publikacji</div>
                        <div class="col-md-3"><h:inputText value="#{bookAddController.year}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3"><h:commandButton value="Dodaj książkę" action="#{bookAddController.addBook()}"/></div>
                    </div>
                </h:form>                
            </ui:define>
        </ui:composition>
    </h:body>
</html>

ent-web/src/main/webapp/adduser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="templates/commonlayout.xhtml">
            <ui:define name="content">
                <h2>Dodaj użytkownika</h2>
                <h:form>
                    <div class="row">
                        <div class="col-md-3">Imię</div>
                        <div class="col-md-3"><h:inputText value="#{userControler.firstName}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Nazwisko</div>
                        <div class="col-md-3"><h:inputText value="#{userControler.lastName}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Adres</div>
                        <div class="col-md-3"><h:inputText value="#{userControler.street}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Miasto</div>
                        <div class="col-md-3"><h:inputText value="#{userControler.city}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3"><h:commandButton value="Dodaj użytkownika" action="#{userControler.addUser()}"/></div>
                    </div>
                </h:form>                
            </ui:define>
        </ui:composition>
    </h:body>
</html>

ent-web/src/main/webapp/adminpage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:body>
        <ui:composition template="templates/commonlayout.xhtml">
            <ui:define name="content">
                <h2>Administracja</h2>
                <h:panelGroup rendered="#{session.getAttribute('userRole') == 'admin'}">
                    <p><h:link value="Dodaj książkę" outcome="addbook.xhtml"/></p>
                    <p><h:link value="Dodaj użytkownika" outcome="adduser.xhtml"/></p>
                    <p><h:link value="Użytkownicy" outcome="listofusers.xhtml"/></p>
                </h:panelGroup>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

ent-web/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui = "http://java.sun.com/jsf/facelets">

    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="templates/commonlayout.xhtml">
            <ui:define name ="content">
                <h2>Zaloguj się</h2>
                <h:form rendered="#{not loginController.userLogged}">
                    Login <h:inputText value="#{loginController.userLogin}"/>
                    Hasło <h:inputSecret value="#{loginController.password}"/>
                    <h:commandButton value="Zaloguj" action="#{loginController.login()}"/>
                </h:form>
                <h:form rendered="#{loginController.userLogged}">
                    <p><h:outputText value="#{session.id}"/></p>
                    <p><h:outputText value="Witaj #{loginController.user.userLogin}"/></p>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

ent-web/src/main/webapp/listofbooks.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="templates/commonlayout.xhtml">
            <ui:define name="content">
                <h2>Lista książek</h2>
                <h:dataTable value="#{bookTableController.booksDTO}" var="book" class="table table-striped table-bordered table-hover table-condensed">
                    <h:column>
                        <f:facet name="header">Tytuł</f:facet>
                            #{book.name}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Autor</f:facet>
                            #{bookTableController.getAuthors(book)}
                    </h:column>
                    <h:column>
                        <f:facet name="header">ISBN</f:facet>
                            #{book.isbn}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Rok wydania</f:facet>
                            #{book.year}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Wypożycz</f:facet>
                        <h:form>
                            <h:commandButton value="Wypożycz" action="#{rentControler.rentBook(book)}"/>
                        </h:form>
                    </h:column>
                </h:dataTable>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

ent-web/src/main/webapp/listofusers.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="templates/commonlayout.xhtml">
            <ui:define name="content">
                <h2>Lista użytkowników</h2>
                <h:dataTable value="#{userControler.users}" var="user" class="table table-striped table-bordered table-hover table-condensed">
                    <h:column>
                        <f:facet name="header">Imię</f:facet>
                        #{user.firstName}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Nazwisko</f:facet>
                        #{user.lastName}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Adres</f:facet>
                        #{user.street}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Miasto</f:facet>
                        #{user.city}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Edit</f:facet>
                    </h:column>
                </h:dataTable>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

ent-web/src/main/webapp/order.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:body>
        <ui:composition template="templates/commonlayout.xhtml">
            <ui:define name="content">
                <h2>Twój koszyk</h2>
                <h:dataTable value="#{rentControler.listOfRentedBooks}" var="book" class="table table-striped table-bordered table-hover table-condensed">
                    <h:column>
                        <f:facet name="header">Tytuł</f:facet>
                            #{book.name}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Kwota</f:facet>
                        10 zł
                    </h:column>
                    <h:column>
                        <f:facet name="header">Anuluj</f:facet>
                        <h:form>
                            <h:commandButton value="Anuluj" action="#{rentControler.cancel(book)}"/>
                        </h:form>
                    </h:column>
                </h:dataTable>
                <h:form>
                    <h:commandButton value="Potwierdzam wypożyczenie" action="#{rentControler.confirmRent()}"/>
                    Razem: #{rentControler.calculatePayment()} zł
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

ent-web/src/main/webapp/templates/commonlayout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    
    <h:head>
        <!-- Bootstrap core CSS -->
        <link href="css/bootstrap.min.css" rel="stylesheet"/>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="css/ie10-viewport-bug-workaround.css" rel="stylesheet"/>
        <!-- Custom styles for this template -->
        <link href="css/starter-template.css" rel="stylesheet"/>
        
        <link href="css/sticky-footer.css" rel="stylesheet"/>
    </h:head>
    <h:body>
        <div class="container">
            <div class="starter-template" style="padding-top: 50px">
                <ui:insert name="header">
                    <ui:include src="header.xhtml"/>
                </ui:insert>
                <ui:insert name="content">
                    <ui:include src="content.xhtml"/>
                </ui:insert>
            </div>
        </div>
        <ui:insert name="footer">
            <ui:include src="footer.xhtml"/>
        </ui:insert>
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script type="text/javascript" src="js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script type="text/javascript" src="js/ie10-viewport-bug-workaround.js"></script>
    </h:body>
</html>

ent-web/src/main/webapp/templates/content.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    
    <h:body>
        <ui:composition>
            <h1>CONTENT!</h1>
        </ui:composition>
    </h:body>
</html>

ent-web/src/main/webapp/templates/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    
    <h:body>
        <ui:composition>
            <hr></hr>
            <footer class="footer">
                <div class="container">
                    <span class="text-muted">Biblioteka v0.8</span>
                </div>
            </footer>
        </ui:composition>
    </h:body>
</html>

ent-web/src/main/webapp/templates/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:body>
        <ui:composition>
            <nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="">Biblioteka</a>
                    </div>
                    <div id="navbar" class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><h:link value="Ksiązki" outcome="listofbooks.xhtml"/></li>
                            <li><h:link value="Moje konto" outcome="account.xhtml" rendered="#{session.getAttribute('userRole') == 'admin' or session.getAttribute('userRole') == 'user'}"/></li>
                            <li><h:link value="Koszyk (Pozycje: #{rentControler.listOfRentedBooks.size()})" outcome="order.xhtml" rendered="#{session.getAttribute('userRole') == 'user'}"/></li>
                            <li><h:link value="Administracja" outcome="adminpage.xhtml" rendered="#{session.getAttribute('userRole') == 'admin'}"/></li>}
                        </ul>
                    </div>
                </div>
            </nav>
        </ui:composition>
    </h:body>
</html>

ent-web/src/main/webapp/templates/noprivilages.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:body>
        <ui:composition>
            <ui:define name="content">
                <h1>BRAK DOSTĘPU!</h1>
                <h1>Zaloguj się na stronie głównej!</h1>
            </ui:define>
        </ui:composition>
    </h:body>
</html>